variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.8-openjdk-17

cache:
  paths:
    - .m2/repository

test:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS test'

java-build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests=true
  artifacts:
    name: "Jar for $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "target/banque-0.0.1-SNAPSHOT.jar"

docker-build:
  image: docker:20.10.16
  stage: build
  needs: ["java-build"]
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/dal-banque/dal-banque:$CI_COMMIT_REF_SLUG target/
    - docker push $CI_REGISTRY/dal-banque/dal-banque:$CI_COMMIT_REF_SLUG