version: "3.8"
services:
    spring-server:
        image: benjil/dal-banque-production:latest
        ports:
            - "8080:8080"
        depends_on:
            - mongo_db

    mongo_db:
        image: mongo:6.0.2
        volumes:
            - './data:/data/db'
        ports:
            - "27017:27017"
