version: "3.8"
services:
    spring-server:
        build:
            image: benjil/dal-banque-staging:latest
        ports:
            - "8080:8080"
        depends_on:
            - mongo_db
        hostname: spring-server
        links:
            - mongo

    mongo_db:
        image: mongo:6.0.2
        volumes:
            - './data:/data/db'
        ports:
            - "27017:27017"
        hostname: mongo
