version: "3.8"
services:
    spring-server:
        image: benjil/dal-banque-production:latest
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - mongo_db