version: "3.8"
services:
    spring-server:
        build:
            context: .
        ports:
            - "8080:8080"
        depends_on:
            - mongo_db
        hostname: spring-server
        links:
            - mongo_db:mongo

    mongo_db:
        image: mongo:6.0.2
        volumes:
            - './data:/data/db'
